export function projectDocuments({ projectName, description, stack }) {
  const today = new Date().toISOString().slice(0, 10);
  return {
    "PRD.md": `# ${projectName} — Product Requirements Document\n\nCreated: ${today}\n\n## Problem\n${description}\n\n## Users and jobs\n- Define the primary user and the job they need done.\n\n## Scope\n- In scope: define concrete user outcomes before implementation.\n- Out of scope: list explicitly to prevent feature creep.\n\n## Acceptance criteria\n- Every feature has testable acceptance criteria.\n- Security and privacy requirements are treated as product requirements.\n`,
    "ARCHITECTURE.md": `# ${projectName} — Architecture\n\n## Stack\n${stack || "To be decided"}\n\n## System boundaries\n- Client, API, data stores, external services, and trust boundaries must be documented here.\n\n## Data classification\n- Public, internal, confidential, restricted.\n- Identify personal data, secrets, and retention/deletion requirements.\n\n## Security architecture\n- Authentication, authorization, session handling, input validation, encryption, audit logging, and incident paths.\n`,
    "RULES.md": `# Engineering & Security Rules\n\n1. Never commit secrets, tokens, private keys, or production credentials.\n2. Enforce authorization server-side for every protected resource and action.\n3. Validate input at trust boundaries; use parameterized queries and safe APIs.\n4. Treat user-controlled URLs, files, templates, and redirects as hostile.\n5. Use least privilege and secure defaults.\n6. Do not log passwords, tokens, financial data, or unnecessary personal data.\n7. Keep dependencies minimal and patched; pin/lock them.\n8. Add tests for authorization, validation, and security regressions.\n9. Call security_review_change after every change before declaring completion.\n`,
    "PHASES.md": `# Delivery Phases\n\n## 0. Discovery\n- Confirm problem, users, scope, data classification, and threats.\n\n## 1. Foundations\n- Establish architecture, auth model, secrets management, linting, tests, and CI.\n\n## 2. MVP\n- Build vertical slices against documented acceptance criteria.\n\n## 3. Security hardening\n- Threat model, dependency review, authz tests, abuse controls, observability.\n\n## 4. Release\n- Security review, privacy check, rollback plan, monitoring, and owner handoff.\n`,
    "DESIGN.md": `# ${projectName} — Design System\n\n## Principles\n- Accessible, clear, responsive, and consistent.\n\n## Foundations\n- Define colors, typography, spacing, elevation, breakpoints, and motion before building screens.\n\n## Accessibility\n- Keyboard navigation, visible focus, semantic HTML, labels, contrast, error messages, and reduced-motion support are required.\n\n## Components\n- Document component states: default, hover, focus, disabled, loading, empty, and error.\n`
  };
}
